# Introduction to NumPy

NumPy (Numerical Python) is a library for fast numerical computing in Python.

It introduces the ndarray, an efficient array object for working with numbers.

In [ ]:
import numpy as np

### NumPy Arrays vs Python Lists

In [ ]:
lst = [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])

Key differences:

- NumPy arrays store elements of the same type

- Much faster for numerical operations

- Support vectorized operations (faster, more readable, less error prone)

### Basic Array Properties

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.shape)      # dimensions
print(arr.size)       # number of elements
print(arr.dtype)      # data type


(4,)
4
int64


### Creating Arrays

In [ ]:
zero_list = np.zeros(5)
one_list = np.ones(5)
zero_list, one_list

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [ ]:
zero_list_2d = np.zeros((2, 3))
one_list_2d = np.ones((3, 2))
zero_list_2d, one_list_2d

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [ ]:
range_list = np.arange(0, 10, 2)
range_list

array([0, 2, 4, 6, 8])

In [ ]:
evenly_spaced_value_list = np.linspace(0, 1, 5)
evenly_spaced_value_list

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Indexing and Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])

10
50


In [ ]:
print(arr[1:4])
print(arr[2:4])
print(arr[:3])
print(arr[::2])

[20 30 40]
[30 40]
[10 20 30]
[10 30 50]


2D Arrays (Matrices)

In [ ]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [ ]:
mat[0, 1]    # Accessing element: row 0, column 1

np.int64(2)

In [ ]:
#Slicing rows and columns
print(mat[:, 1])    # all rows, column 1
print(mat[1, :])    # row 1, all columns

[2 5]
[4 5 6]


### Vectorized Operations (Very Important)

In [ ]:
lst = [1, 2, 3]
[x * 2 for x in lst]


[2, 4, 6]

In [ ]:
arr = np.array([1, 2, 3])
arr * 2

array([2, 4, 6])

In [ ]:
print(arr + 10)
print(arr ** 2)
print(arr / 2)


[11 12 13]
[1 4 9]
[0.5 1.  1.5]


### Boolean Operations & Filtering

In [ ]:
arr = np.array([10, 15, 20, 25, 30])
arr > 20


array([False, False, False,  True,  True])

In [ ]:
arr[arr > 20]

array([25, 30])

### Useful Aggregate Functions

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

15
3.0
1
5
1.4142135623730951


In [ ]:
print(mat.sum(axis=0))   # column-wise
print(mat.sum(axis=1))   # row-wise

[5 7 9]
[ 6 15]


### Reshaping Arrays

In [ ]:
arr = np.arange(12)
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.reshape((-1, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### Copy vs View (Important Concept)

In [ ]:
arr = np.array([1, 2, 3])
view = arr
copy = arr.copy()

view[0] = 99
arr, copy

(array([99,  2,  3]), array([1, 2, 3]))

In [ ]:
copy[1] = 100
arr, copy

(array([99,  2,  3]), array([  1, 100,   3]))

### Random Numbers

In [ ]:
print(np.random.rand(5))          # uniform [0,1)
print(np.random.randint(1, 10, size=5))   # integers
np.random.seed(0)  # reproducibility

[0.80091075 0.52047748 0.67887953 0.72063265 0.58201979]
[1 5 8 4 3]


### When to Use NumPy

Use NumPy when you need:

- Numerical computation

- Large datasets

- Matrix / vector math

- Performance

Avoid NumPy for:

- Mixed data types

- General-purpose data storage (use lists or dicts)

### Participation Question

Create an array of size 10, consisting random integer numbers ranging from 1 to 20

1. Select only the even numbers

2. Square them

3. Compute the mean of the result
